import type { Config } from "tailwindcss";

/**
 * Design tokens for the product's visual system (see Job_Tracker_Design_Spec).
 *
 * One violet accent, matching the mockups, where an earlier revision split
 * blue (ordinary actions) from purple (AI). `brand` and `ai` therefore now
 * resolve to the same hue and are kept as separate tokens only so the two
 * roles stay greppable.
 *
 * Because hue no longer separates them, AI surfaces are marked structurally
 * instead — the sparkle glyph, the "Generated by AI" provenance badge, and the
 * tinted panel header. Anything computed rather than generated (the
 * dashboard's insight strip) deliberately wears neutral slate so it can't be
 * mistaken for model output.
 */
const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        canvas: "#F8FAFC",
        surface: "#FFFFFF",
        subtle: "#F1F5F9",
        border: "#E2E8F0",
        ink: "#0F172A",
        muted: "#64748B",
        brand: {
          DEFAULT: "#7C3AED",
          hover: "#6D28D9",
          soft: "#F5F3FF",
          ring: "#DDD6FE",
        },
        // Same hue as `brand` — see the note above on how AI is marked now.
        ai: {
          DEFAULT: "#7C3AED",
          hover: "#6D28D9",
          soft: "#F5F3FF",
          ring: "#DDD6FE",
        },
        success: { DEFAULT: "#22C55E", soft: "#F0FDF4", ring: "#BBF7D0" },
        warning: { DEFAULT: "#F59E0B", soft: "#FFFBEB", ring: "#FDE68A" },
        danger: { DEFAULT: "#EF4444", soft: "#FEF2F2", ring: "#FECACA" },
      },
      fontFamily: {
        sans: ["var(--font-inter)", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      boxShadow: {
        card: "0 1px 2px 0 rgb(15 23 42 / 0.04), 0 1px 3px 0 rgb(15 23 42 / 0.06)",
        "card-hover":
          "0 4px 6px -1px rgb(15 23 42 / 0.07), 0 2px 4px -2px rgb(15 23 42 / 0.05)",
        pop: "0 10px 15px -3px rgb(15 23 42 / 0.08), 0 4px 6px -4px rgb(15 23 42 / 0.05)",
      },
      keyframes: {
        "fade-in": {
          from: { opacity: "0", transform: "translateY(4px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "100%": { transform: "translateX(100%)" },
        },
      },
      animation: {
        "fade-in": "fade-in 200ms ease-out",
        shimmer: "shimmer 1.6s infinite",
      },
      transitionDuration: {
        DEFAULT: "150ms",
      },
    },
  },
  plugins: [],
};

export default config;
