"use client";

import { useEffect, useState, type ReactNode } from "react";
import Link from "next/link";
import { formatDate } from "@/lib/format";
import { cardClassName } from "@/lib/ui";
import { IconAlert, IconSparkles } from "@/components/icons";

/**
 * Shared building blocks for the AI surfaces (resume tips, tailored resume,
 * cover letter, drafted answers, LinkedIn notes).
 *
 * Violet is the product's single accent, so hue alone no longer says "a model
 * wrote this". The sparkle glyph and the "Generated by AI" provenance badge
 * carry that meaning instead, and they appear when — and only when — a model
 * produced what's on screen.
 */

/** Panel wrapper for an AI section: sparkle, title, blurb, header actions. */
export function AiPanel({
  title,
  description,
  status,
  actions,
  children,
}: {
  title: string;
  description: ReactNode;
  /** One-line state summary, right of the title. */
  status?: ReactNode;
  actions?: ReactNode;
  children: ReactNode;
}) {
  return (
    <section className={cardClassName}>
      {/*
        Stacks below `sm` rather than relying on flex-wrap. The text column is
        `min-w-0 flex-1`, so on a narrow screen it would shrink to a few
        characters instead of pushing the buttons onto their own line — the
        title wrapped one word per line beside a full-width button row.
      */}
      <div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex min-w-0 flex-1 gap-3">
          <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-ai-soft text-ai ring-1 ring-inset ring-ai-ring">
            <IconSparkles size={18} />
          </span>
          <div className="min-w-0">
            <div className="flex flex-wrap items-center gap-2">
              <h2 className="text-base font-bold text-ink">{title}</h2>
              {status}
            </div>
            <p className="mt-1 text-sm text-muted">{description}</p>
          </div>
        </div>
        {actions && (
          <div className="flex shrink-0 flex-wrap items-center gap-2">{actions}</div>
        )}
      </div>

      <div className="border-t border-border p-5">{children}</div>
    </section>
  );
}

export type AiState =
  | "loading"
  | "no-resume"
  | "not-generated"
  | "up-to-date"
  | "stale"
  | "edited"
  | "working";

const STATE_CHIPS: Record<Exclude<AiState, "loading">, { label: string; className: string }> = {
  "no-resume": {
    label: "No resume",
    className: "bg-subtle text-muted ring-border",
  },
  "not-generated": {
    label: "Not generated",
    className: "bg-subtle text-muted ring-border",
  },
  "up-to-date": {
    label: "Up to date",
    className: "bg-success-soft text-emerald-700 ring-success-ring",
  },
  stale: {
    label: "Inputs changed",
    className: "bg-warning-soft text-amber-700 ring-warning-ring",
  },
  edited: {
    label: "Edited by you",
    className: "bg-brand-soft text-brand ring-brand-ring",
  },
  working: {
    label: "Generating…",
    className: "bg-ai-soft text-ai ring-ai-ring",
  },
};

/** The staleness chip that sits beside an AI panel's title. */
export function AiStateChip({ state }: { state: AiState }) {
  if (state === "loading") return null;
  const chip = STATE_CHIPS[state];
  return (
    <span
      className={`inline-flex shrink-0 items-center gap-1 whitespace-nowrap rounded-full px-2 py-0.5 text-[11px] font-semibold ring-1 ring-inset ${chip.className}`}
    >
      {state === "working" && (
        <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-current" />
      )}
      {chip.label}
    </span>
  );
}

/**
 * Provenance line under generated content: that a model wrote it, when, and
 * whether it still matches the inputs it was made from.
 */
export function AiProvenance({
  generatedAt,
  upToDate,
  edited,
  extra,
}: {
  generatedAt: string;
  upToDate: boolean;
  edited?: boolean;
  /** Leading detail, e.g. a word count. */
  extra?: string;
}) {
  return (
    <div className="flex flex-wrap items-center gap-x-2 gap-y-1 border-t border-border pt-3 text-xs text-muted">
      <span className="inline-flex items-center gap-1 rounded-full bg-ai-soft px-2 py-0.5 font-semibold text-ai ring-1 ring-inset ring-ai-ring">
        <IconSparkles size={11} />
        Generated by AI
      </span>
      {extra && <span className="font-medium">{extra}</span>}
      <span>·</span>
      <span>{formatDate(generatedAt)}</span>
      {edited && (
        <>
          <span>·</span>
          <span className="font-semibold text-brand">Edited by you</span>
        </>
      )}
      <span>·</span>
      <span className={upToDate ? "" : "font-semibold text-amber-700"}>
        {upToDate
          ? "Matches your current resume and this posting"
          : "Your resume or this posting changed since"}
      </span>
    </div>
  );
}

/**
 * What the model is doing while a request is in flight.
 *
 * The stages are real phases of the server's work and advance on a timer, so
 * this deliberately shows no percentage or ETA — it explains the wait rather
 * than claiming to measure it.
 */
export function AiProgress({ steps }: { steps: string[] }) {
  const [active, setActive] = useState(0);

  useEffect(() => {
    setActive(0);
    const timer = setInterval(() => {
      setActive((current) => Math.min(current + 1, steps.length - 1));
    }, 6000);
    return () => clearInterval(timer);
  }, [steps.length]);

  return (
    <div className="rounded-xl border border-ai-ring bg-ai-soft/60 p-4">
      <ol className="space-y-2.5">
        {steps.map((step, index) => {
          const done = index < active;
          const current = index === active;
          return (
            <li key={step} className="flex items-center gap-2.5 text-sm">
              <span
                className={`flex h-5 w-5 shrink-0 items-center justify-center rounded-full text-[10px] font-bold ${
                  done
                    ? "bg-ai text-white"
                    : current
                      ? "bg-ai/15 text-ai ring-2 ring-ai/30"
                      : "bg-surface text-muted ring-1 ring-border"
                }`}
              >
                {done ? "✓" : index + 1}
              </span>
              <span
                className={
                  current
                    ? "font-semibold text-ai"
                    : done
                      ? "text-muted"
                      : "text-muted/70"
                }
              >
                {step}
              </span>
              {current && (
                <span className="ml-auto flex gap-1" aria-hidden>
                  {[0, 1, 2].map((dot) => (
                    <span
                      key={dot}
                      className="h-1.5 w-1.5 animate-pulse rounded-full bg-ai"
                      style={{ animationDelay: `${dot * 200}ms` }}
                    />
                  ))}
                </span>
              )}
            </li>
          );
        })}
      </ol>
      <p className="mt-3 text-xs text-muted">
        This usually takes under a minute. You can keep working in other tabs.
      </p>
    </div>
  );
}

/** Shimmer placeholder for content that's loading. */
export function AiSkeleton({ lines = 4 }: { lines?: number }) {
  return (
    <div className="space-y-2.5" aria-hidden>
      {Array.from({ length: lines }).map((_, index) => (
        <div
          key={index}
          className="h-3.5 animate-pulse rounded bg-subtle"
          style={{ width: `${100 - (index % 3) * 14}%` }}
        />
      ))}
    </div>
  );
}

/**
 * A rewrite, shown as what it was and what it became.
 *
 * Being able to audit every change is the trust story for the generated
 * documents, so the original is always legible — struck through and recessive,
 * never hidden behind a toggle.
 */
export function AiDiff({
  before,
  after,
  reason,
}: {
  before?: string | null;
  after: string;
  reason?: string;
}) {
  const changed = Boolean(before && before !== after);

  return (
    <div className="rounded-xl border border-border bg-subtle/50 p-3">
      {changed && (
        <p className="text-sm text-muted line-through decoration-danger/40">{before}</p>
      )}
      <p className={`text-sm font-medium text-ink ${changed ? "mt-1.5" : ""}`}>
        {!changed && !before && (
          <span className="mr-1.5 rounded bg-success-soft px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wide text-emerald-700">
            New
          </span>
        )}
        {after}
      </p>
      {reason && <p className="mt-1.5 text-xs text-muted">{reason}</p>}
    </div>
  );
}

/** Shown when a feature can't run because there's no resume on file. */
export function NoResumeNotice({ action }: { action: string }) {
  return (
    <div className="flex items-start gap-3 rounded-xl border border-warning-ring bg-warning-soft p-4">
      <IconAlert size={18} className="mt-0.5 shrink-0 text-amber-600" />
      <div>
        <p className="text-sm font-semibold text-ink">Upload your resume first</p>
        <p className="mt-0.5 text-sm text-muted">
          {action} reads your resume.{" "}
          <Link href="/settings" className="font-semibold text-brand hover:underline">
            Add it in Settings
          </Link>{" "}
          to unlock this and the other AI features.
        </p>
      </div>
    </div>
  );
}

/** Inline error inside an AI panel. */
export function AiError({ message }: { message: string }) {
  return (
    <div className="flex items-start gap-2.5 rounded-xl border border-danger-ring bg-danger-soft p-3">
      <IconAlert size={17} className="mt-px shrink-0 text-danger" />
      <p className="text-sm font-medium text-red-700">{message}</p>
    </div>
  );
}
